### ISSUE TITLE
Pull from Gmail to Google Sheet

### ISSUE THREAD

**Issue by Briettny** [c0de-e/Finance-Automation#1]
I would like to explore pulling information from an email of a bill to a specific tab, House Bills, in a Google Sheet. From most important to least important, it would be helpful for a tool to pull the bill name, bill amount, and bill due date. Emails from the following are already labeled as 'Bills'.

1. Xfinity <online.communications@alerts.comcast.net>
2. Dominion Energy <paperlessbill@domenergyuteb.com>
3. noreply@xpressbillpay.com

The above utility bills are usually all sent by the 25th of each month. Thus, I would like a recurring pull scheduled.

**Comment by Briettny** [comment]
1. Xfinity - Payment date:
2. Lehi City -  Payment Scheduled for:
3. Dominion - Bank Payment 2023-06-07

**Comment by c0de-e** [comment]
Done. 
Find link to the commit [here](https://github.com/c0de-e/Finance-Automation/commit/6b06ab389721464802a34a5aca90bf3c5470288c).
