### ISSUE TITLE
Divide Bill Amount

### ISSUE THREAD

**Issue by Briettny** [c0de-e/Finance-Automation#2]
Once the information is pulled into the Google Sheets, dividing the amount due by 2 would be helpful. This could be in 2 columns: a column of the total amount and another of the amount divided by 2. Or, 1 column of the total amount due divided by 2. 

There is no preference.

**Comment by c0de-e** [comment]
Done.
Find link to the commit [here](https://github.com/c0de-e/Finance-Automation/commit/6b06ab389721464802a34a5aca90bf3c5470288c).
