### ISSUE TITLE
Google Sheet + Google Calendar Integration

### ISSUE THREAD

**Issue by Briettny** [c0de-e/Finance-Automation#4]
**Is your feature request related to a problem? Please describe.**
I'm anxious when unable to keep track of bill due dates. Right now, I have a general deadline that all bills will notify me by the end of a month. The problem is a lack of accuracy. 

**Describe the solution you'd like**
I would like the Bill Auto Pay calendar to update with an event created based on the due date included in an email from Dominion and Xpress Bill Pay. 

**Describe alternatives you've considered**
Instead of an event, I have also considered a Google task. This is because Google tasks can be displayed within a calendar. 

**Additional context**
Screenshot of calendars, if helpful.
<img width="164" alt="image" src="https://github.com/c0de-e/Finance-Automation/assets/111247311/13db20ee-61e6-41e1-873c-58144f8c4b88">

**Comment by c0de-e** [comment]
Added functionality with commit 2726a1283aac47f2442d572bd5e2c7559d44dceb.
